version: "3"
services:
  app:
    image: express-google:latest

    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "3001:3001"

    environment:
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
      JWT_SECRET: "jwt"
